name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    
    strategy:
      matrix:
        experimental: [false]
        
        os:
          - ubuntu
          - macos
        
        ruby:
          - 2.7
          - 3.0
          - 3.1
        
        gemfile: 
          - gems/rack-v2.rb
        
        include:
          - experimental: true
            os: ubuntu
            ruby: head
          - experimental: false
            os: ubuntu
            ruby: 3.1
            gemfile: gems/rack-v2.rb
          - experimental: false
            os: ubuntu
            ruby: 3.1
            gemfile: gems/rack-v3.rb
          - experimental: true
            os: ubuntu
            ruby: 3.1
            gemfile: gems/rack-head.rb
    
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    
    - name: Install dependencies
      run: ${{matrix.env}} bundle install
    
    - name: Run tests
      run: ${{matrix.env}} bundle exec rake
